

class Header extends HTMLElement {
    constructor() {
        super();
    }

    connectedCallback() {
        this.innerHTML = `<head>
    <title></title>

    </head>
    <body >
        
<div class="header-spacing"></div>
<div class="stdheader autogenerated">
    <h1 class="maintitle">Sir Thomas More</h1>
</div>
    </body>`
    }
}

customElements.define("header-component", Header);
